# Generated by Django 2.2.5 on 2019-11-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='código',
            new_name='codigo',
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=300),
        ),
    ]
